name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#   build-android:
#     name: Build Android APK
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - name: Install dependencies
#         run: flutter pub get

# #      - name: Analyze code
# #        run: flutter analyze

# #      - name: Run tests
# #        run: flutter test

#       - name: Build APK
#         run: flutter build apk --release

#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: android-apk
#           path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS for TestFlight
    runs-on: macos-latest
    # needs: build-android

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      # - name: Fastlane Match Setup
      #   run: |
      #     cd ios
      #     bundle exec fastlane run setup_ci
      #     bundle exec fastlane match appstore  --readonly
        # env:

      - name: Deploy to TestFlight
        run: |
          cd ios
          bundle exec fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          # APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          # APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          # APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}